apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: api
  name: api
  namespace: ne
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8000
    - name: "5456"
      port: 5456
      targetPort: 5456
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
