apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8000
    - name: "5456"
      port: 5456
      targetPort: 5456
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
