apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ne
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: api
    spec:
      containers:
        - args:
            - python
            - care_api/manage.py
            - runserver
            - 0.0.0.0:8000
          image: shiywang/neapi:latest
          name: api
          # imagePullPolicy: Always
          ports:
            - containerPort: 8000
            - containerPort: 5456
      hostname: api
      restartPolicy: Always