apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ne
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        # - args:
            # - python
            # - care_api/manage.py
            # - runserver
            # - 0.0.0.0:8000
        - image: shiywang/neapi:test1
          name: api
          ports:
            - containerPort: 8000
            - containerPort: 5456
          resources:
            requests:
              memory: "64Mi"
              cpu: "500m"
            limits:
              memory: "64Mi"
              cpu: "500m"
      restartPolicy: Always