apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
  namespace: ne
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy: {}
  template:
    metadata:
      labels:
        app: db
    spec:
      shareProcessNamespace: true
      containers:
        - image: nelab/nedb:latest
          name: db
          # imagePullPolicy: Always
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}
