apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
  namespace: ne
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodeserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: nodeserver
    spec:
      containers:
        - args:
            - node
            - middleman.js
          image: shiywang/nenode:latest
          name: nodeserver
          ports:
            - containerPort: 3001
            - containerPort: 4000
          resources: {}
          # volumeMounts:
          #   - mountPath: /code
          #     name: nodeserver-claim0
      hostname: nodeserver
      restartPolicy: Always
      # volumes:
      #   - name: nodeserver-claim0
      #     persistentVolumeClaim:
      #       claimName: nodeserver-claim0
status: {}
