apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodeserver
  name: nodeserver
  namespace: ne
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    app: nodeserver
status:
  loadBalancer: {}
