apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: nodeserver
  name: nodeserver
spec:
  ports:
    - name: "3009"
      port: 3009
      targetPort: 3001
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    io.kompose.service: nodeserver
status:
  loadBalancer: {}
