apiVersion: v1
kind: Service
metadata:
  labels:
    app: ne
  name: web
  namespace: ne
spec:
  type: NodePort
  ports:
      port: 80
      targetPort: 80
      nodePort: 31000
  selector:
    app: ne