apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: ne
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - args:
            - API_SERVICE_HOST=$API_SERVICE_HOST
            - NODESERVER_SERVICE_HOST=$NODESERVER_SERVICE_HOST
            - npm
            - start
            - --prefix
            - care_app/
          image: nelab/neweb:latest
          name: web
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "800Mi"
              cpu: "500m"
            limits:
              memory: "800Mi"
              cpu: "500m"
