apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: ne
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ne
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ne
    spec:
      containers:
        - args:
            - npm
            - start
            - --prefix
            - care_app/
          image: nelab/neweb:latest
          name: web
          # imagePullPolicy: Always
          ports:
            - containerPort: 3000
      restartPolicy: Always