apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: web
  name: web
  namespace: ne
spec:
  type: NodePort
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3000
      nodePort: 30007
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
