apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: ne
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - args:
            - npm
            - start
            - --prefix
            - care_app/
          image: shiywang/neweb:latest
          name: web
          ports:
            - containerPort: 3000
          resources: {}
          stdin: true
          # volumeMounts:
          #   - mountPath: /code
          #     name: web-claim0
      restartPolicy: Always
      # volumes:
      #   - name: web-claim0
      #     persistentVolumeClaim:
      #       claimName: web-claim0
status: {}
